<?php

namespace Proxies\__CG__\Main\RatetradeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CanadaCities extends \Main\RatetradeBundle\Entity\CanadaCities implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaCities' . "\0" . 'city', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaCities' . "\0" . 'cityUrl', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaCities' . "\0" . 'provinceId', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaCities' . "\0" . 'showFlag', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaCities' . "\0" . 'id', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaCities' . "\0" . 'urlLink', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaCities' . "\0" . 'urlFlag');
        }

        return array('__isInitialized__', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaCities' . "\0" . 'city', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaCities' . "\0" . 'cityUrl', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaCities' . "\0" . 'provinceId', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaCities' . "\0" . 'showFlag', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaCities' . "\0" . 'id', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaCities' . "\0" . 'urlLink', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaCities' . "\0" . 'urlFlag');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CanadaCities $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCityUrl($cityUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCityUrl', array($cityUrl));

        return parent::setCityUrl($cityUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getCityUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCityUrl', array());

        return parent::getCityUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvinceId($provinceId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvinceId', array($provinceId));

        return parent::setProvinceId($provinceId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvinceId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvinceId', array());

        return parent::getProvinceId();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowFlag($showFlag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowFlag', array($showFlag));

        return parent::setShowFlag($showFlag);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowFlag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowFlag', array());

        return parent::getShowFlag();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlLink($urlLink)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlLink', array($urlLink));

        return parent::setUrlLink($urlLink);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlLink', array());

        return parent::getUrlLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlFlag($urlFlag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlFlag', array($urlFlag));

        return parent::setUrlFlag($urlFlag);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlFlag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlFlag', array());

        return parent::getUrlFlag();
    }

}
