<?php

namespace Proxies\__CG__\Main\RatetradeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WpPosts extends \Main\RatetradeBundle\Entity\WpPosts implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postAuthor', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postDate', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postDateGmt', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postContent', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postTitle', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postExcerpt', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postStatus', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'commentStatus', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'pingStatus', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postPassword', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postName', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'toPing', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'pinged', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postModified', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postModifiedGmt', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postContentFiltered', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postParent', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'guid', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'menuOrder', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postType', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postMimeType', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'commentCount', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'id');
        }

        return array('__isInitialized__', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postAuthor', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postDate', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postDateGmt', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postContent', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postTitle', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postExcerpt', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postStatus', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'commentStatus', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'pingStatus', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postPassword', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postName', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'toPing', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'pinged', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postModified', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postModifiedGmt', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postContentFiltered', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postParent', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'guid', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'menuOrder', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postType', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'postMimeType', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'commentCount', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\WpPosts' . "\0" . 'id');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WpPosts $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setPostAuthor($postAuthor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostAuthor', array($postAuthor));

        return parent::setPostAuthor($postAuthor);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostAuthor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostAuthor', array());

        return parent::getPostAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostDate($postDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostDate', array($postDate));

        return parent::setPostDate($postDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostDate', array());

        return parent::getPostDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostDateGmt($postDateGmt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostDateGmt', array($postDateGmt));

        return parent::setPostDateGmt($postDateGmt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostDateGmt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostDateGmt', array());

        return parent::getPostDateGmt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostContent($postContent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostContent', array($postContent));

        return parent::setPostContent($postContent);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostContent', array());

        return parent::getPostContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostTitle($postTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostTitle', array($postTitle));

        return parent::setPostTitle($postTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostTitle', array());

        return parent::getPostTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostExcerpt($postExcerpt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostExcerpt', array($postExcerpt));

        return parent::setPostExcerpt($postExcerpt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostExcerpt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostExcerpt', array());

        return parent::getPostExcerpt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostStatus($postStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostStatus', array($postStatus));

        return parent::setPostStatus($postStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostStatus', array());

        return parent::getPostStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentStatus($commentStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentStatus', array($commentStatus));

        return parent::setCommentStatus($commentStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentStatus', array());

        return parent::getCommentStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPingStatus($pingStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPingStatus', array($pingStatus));

        return parent::setPingStatus($pingStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getPingStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPingStatus', array());

        return parent::getPingStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostPassword($postPassword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostPassword', array($postPassword));

        return parent::setPostPassword($postPassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostPassword', array());

        return parent::getPostPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostName($postName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostName', array($postName));

        return parent::setPostName($postName);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostName', array());

        return parent::getPostName();
    }

    /**
     * {@inheritDoc}
     */
    public function setToPing($toPing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToPing', array($toPing));

        return parent::setToPing($toPing);
    }

    /**
     * {@inheritDoc}
     */
    public function getToPing()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToPing', array());

        return parent::getToPing();
    }

    /**
     * {@inheritDoc}
     */
    public function setPinged($pinged)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPinged', array($pinged));

        return parent::setPinged($pinged);
    }

    /**
     * {@inheritDoc}
     */
    public function getPinged()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPinged', array());

        return parent::getPinged();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostModified($postModified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostModified', array($postModified));

        return parent::setPostModified($postModified);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostModified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostModified', array());

        return parent::getPostModified();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostModifiedGmt($postModifiedGmt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostModifiedGmt', array($postModifiedGmt));

        return parent::setPostModifiedGmt($postModifiedGmt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostModifiedGmt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostModifiedGmt', array());

        return parent::getPostModifiedGmt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostContentFiltered($postContentFiltered)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostContentFiltered', array($postContentFiltered));

        return parent::setPostContentFiltered($postContentFiltered);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostContentFiltered()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostContentFiltered', array());

        return parent::getPostContentFiltered();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostParent($postParent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostParent', array($postParent));

        return parent::setPostParent($postParent);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostParent', array());

        return parent::getPostParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setGuid($guid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGuid', array($guid));

        return parent::setGuid($guid);
    }

    /**
     * {@inheritDoc}
     */
    public function getGuid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuid', array());

        return parent::getGuid();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenuOrder($menuOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenuOrder', array($menuOrder));

        return parent::setMenuOrder($menuOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenuOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenuOrder', array());

        return parent::getMenuOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostType($postType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostType', array($postType));

        return parent::setPostType($postType);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostType', array());

        return parent::getPostType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostMimeType($postMimeType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostMimeType', array($postMimeType));

        return parent::setPostMimeType($postMimeType);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostMimeType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostMimeType', array());

        return parent::getPostMimeType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentCount($commentCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentCount', array($commentCount));

        return parent::setCommentCount($commentCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentCount', array());

        return parent::getCommentCount();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

}
