<?php

namespace Proxies\__CG__\Main\RatetradeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MetaData extends \Main\RatetradeBundle\Entity\MetaData implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\MetaData' . "\0" . 'page', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\MetaData' . "\0" . 'pageTitle', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\MetaData' . "\0" . 'pageMetaDesc', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\MetaData' . "\0" . 'pageMetaKey', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\MetaData' . "\0" . 'pageContent', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\MetaData' . "\0" . 'id');
        }

        return array('__isInitialized__', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\MetaData' . "\0" . 'page', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\MetaData' . "\0" . 'pageTitle', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\MetaData' . "\0" . 'pageMetaDesc', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\MetaData' . "\0" . 'pageMetaKey', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\MetaData' . "\0" . 'pageContent', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\MetaData' . "\0" . 'id');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MetaData $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setPage($page)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPage', array($page));

        return parent::setPage($page);
    }

    /**
     * {@inheritDoc}
     */
    public function getPage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPage', array());

        return parent::getPage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageTitle($pageTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageTitle', array($pageTitle));

        return parent::setPageTitle($pageTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageTitle', array());

        return parent::getPageTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageMetaDesc($pageMetaDesc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageMetaDesc', array($pageMetaDesc));

        return parent::setPageMetaDesc($pageMetaDesc);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageMetaDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageMetaDesc', array());

        return parent::getPageMetaDesc();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageMetaKey($pageMetaKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageMetaKey', array($pageMetaKey));

        return parent::setPageMetaKey($pageMetaKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageMetaKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageMetaKey', array());

        return parent::getPageMetaKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageContent($pageContent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageContent', array($pageContent));

        return parent::setPageContent($pageContent);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageContent', array());

        return parent::getPageContent();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

}
