<?php

namespace Proxies\__CG__\Main\RatetradeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CanadaProvince extends \Main\RatetradeBundle\Entity\CanadaProvince implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaProvince' . "\0" . 'province', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaProvince' . "\0" . 'provinceUrl', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaProvince' . "\0" . 'shortform', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaProvince' . "\0" . 'id', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaProvince' . "\0" . 'urlFlag', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaProvince' . "\0" . 'urlLink');
        }

        return array('__isInitialized__', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaProvince' . "\0" . 'province', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaProvince' . "\0" . 'provinceUrl', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaProvince' . "\0" . 'shortform', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaProvince' . "\0" . 'id', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaProvince' . "\0" . 'urlFlag', '' . "\0" . 'Main\\RatetradeBundle\\Entity\\CanadaProvince' . "\0" . 'urlLink');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CanadaProvince $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setProvince($province)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvince', array($province));

        return parent::setProvince($province);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvince()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvince', array());

        return parent::getProvince();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvinceUrl($provinceUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvinceUrl', array($provinceUrl));

        return parent::setProvinceUrl($provinceUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvinceUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvinceUrl', array());

        return parent::getProvinceUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setShortform($shortform)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShortform', array($shortform));

        return parent::setShortform($shortform);
    }

    /**
     * {@inheritDoc}
     */
    public function getShortform()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShortform', array());

        return parent::getShortform();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlFlag($urlFlag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlFlag', array($urlFlag));

        return parent::setUrlFlag($urlFlag);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlFlag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlFlag', array());

        return parent::getUrlFlag();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlLink($urlLink)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlLink', array($urlLink));

        return parent::setUrlLink($urlLink);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlLink', array());

        return parent::getUrlLink();
    }

}
